import { createVuetify } from 'vuetify'
import {
  VAlert,
  VApp,
  VAppBar,
  VAppBarTitle,
  VAvatar,
  VBadge,
  VBottomNavigation,
  VBtn,
  VBtnToggle,
  VCard,
  VCheckbox,
  VChip,
  VDivider,
  VIcon,
  VImg,
  VList,
  VListItem,
  VListItemTitle,
  VMain,
  VMenu,
  VNavigationDrawer,
  VProgressCircular,
  VProgressLinear,
  VRadio,
  VRadioGroup,
  VSelect,
  VSkeletonLoader,
  VSnackbar,
  VSwitch,
  VTab,
  VTabs,
  VTextField,
  VTooltip,
  VWindow,
  VWindowItem,
} from 'vuetify/components'

export default createVuetify({
  components: {
    VAlert,
    VApp,
    VAppBar,
    VAppBarTitle,
    VAvatar,
    VBadge,
    VBottomNavigation,
    VBtn,
    VBtnToggle,
    VCard,
    VCheckbox,
    VChip,
    VDivider,
    VIcon,
    VImg,
    VList,
    VListItem,
    VListItemTitle,
    VMain,
    VMenu,
    VNavigationDrawer,
    VProgressCircular,
    VProgressLinear,
    VRadio,
    VRadioGroup,
    VSelect,
    VSkeletonLoader,
    VSnackbar,
    VSwitch,
    VTab,
    VTabs,
    VTextField,
    VTooltip,
    VWindow,
    VWindowItem,
  },
  defaults: {
    VBtn: { rounded: 'lg', elevation: 0 },
    VCard: { rounded: 'xl', elevation: 0 },
    VTextField: { variant: 'outlined', density: 'comfortable', color: 'primary' },
    VSelect: { variant: 'outlined', density: 'comfortable', color: 'primary' },
    VCheckbox: { color: 'primary', hideDetails: true },
    VChip: { rounded: 'lg' },
    VTooltip: { location: 'bottom' },
  },
  theme: {
    defaultTheme: 'pocketLight',
    themes: {
      pocketLight: {
        dark: false,
        colors: {
          background: '#f5f4ee',
          surface: '#ffffff',
          'surface-variant': '#ebe9df',
          primary: '#214ee5',
          secondary: '#153447',
          accent: '#d7ff5f',
          success: '#168568',
          warning: '#c56b16',
          error: '#c94545',
          info: '#3177a9',
          'on-background': '#1f2529',
          'on-surface': '#1f2529',
        },
      },
    },
  },
})
